project:
  type: book

book:
  title: "Single-source capture-recapture models using R"
  author: "Maciej Beręsewicz, Piotr Chlebicki"
  date: today
  chapters:
    - index.qmd
    - intro/intro.qmd
    - ch1/theory.qmd
    - ch2/popsize.qmd
    - ch3/package.qmd    
    - ch4/case-studies.qmd       
    - conclusions/summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

